### ISSUE TITLE
Multiple files with same filename, ZGCTS_BADI_TOGGL.asx.json Cannot find .abapgit.xml - Is this an abapGit repository?

### ISSUE THREAD

**Issue by jhooli** [SAP-samples/s4hana-gcts-badi#1]
Hello,
Not able to pull this. Getting messages 
"Multiple files with same filename, ZGCTS_BADI_TOGGL.asx.json"
and
"Cannot find .abapgit.xml - Is this an abapGit repository?"

**Comment by keller491** [comment]
Hello 
I'm having the same issue. How did you resolve this?
Cheers,
